### App Settings #############################################
# Update every [10] minutes
update_rate: 10
metar_file: /tmp/metar
taf_file: /tmp/taf
log_file: /var/log/metar_map.log
error_log_file: /var/log/metar_map.error.log
###############################################################

### LED Settings #############################################
# LED Brightness

# LED Colors for various conditions.
# All colors are an array of R, G, B values.
led:
  brightness: 10
  colors:
    vfr: '#04a60e'
    marginal: '#032ef1'
    ifr: '#c40000'
###############################################################




### Hardware Settings #########################################
# A list (array) of airports to be displayed on the map
#
# The order of this list must match the way the LEDs are
# wired otherwise you will get incorrect results
airports:
  - KFWN
  - KSMQ
  - KMMU
  - KLDJ
  - KEWR
  - KCDW
  - KTEB
  - KLGA
  - KJFK
  - KHPN
  - KDXR
  - KFRG
  - KISP
  - KBDR
  - KHVN
  - KHWV
  - KFOK
  - KSNC
  - KHTO
  - KGON
  - KWST
###############################################################
